### ISSUE TITLE
EI_job_00.txt Error:  File "/home/ubuntu/src/flex_extract/Source/Python/Mods/checks.py", line 305, in check_step     import numpy as np ImportError: No module named numpy

### ISSUE THREAD

**Issue by XunZhangNJU** [Xunius/flex_extract_helper#1]
flex_extract version: V7.1.2 and local model

When download the flex_extract_helper, and modified the header part of  download.py:

`FLEX_EXTRACT_FOLDER='/home/ubuntu/src/flex_extract/'     # FLEX_EXTRACT intallation folder
OUTPUTDIR='/home/ubuntu/data/'               # folder to save outputs

CONTROL_FILE='CONTROL_EI.public'  # CONTROL file used as default
START_DATE='20190829'             # start date
END_DATE='20191231'               # end date
DAYS_PER_JOB=3                    # number of days to retrieve in each sub-job
TIME_OUT=3*60*60                  # seconds, timeout for the submit.py call
TIME_OUT_RETRY=2                  # number of retries if sumbit.py times out
N_WORKERS=6                       # max number of parallel retrievals to launch.
JOB_PREFIX='EI_job'               # prefix string for all sub-jobs
COPY_CONTROL=True                 # whether to make a copy of the CONTROL file for each sub-job

DRY=False                          # If True, only print a summary.`

I changed my own flex_extract root, and changed my own OUTPUTDIR, then run:

python3 download.py

The EI_job_xx.txt, the error shows that:
Traceback (most recent call last):
  File "/home/ubuntu/src/flex_extract/Source/Python/submit.py", line 268, in <module>
    main()
  File "/home/ubuntu/src/flex_extract/Source/Python/submit.py", line 97, in main
    c, ppid, queue, job_template = setup_controldata()
  File "/home/ubuntu/src/flex_extract/Source/Python/Mods/tools.py", line 115, in setup_controldata
    c.check_conditions(args.queue)
  File "/home/ubuntu/src/flex_extract/Source/Python/Classes/ControlFile.py", line 611, in check_conditions
    self.step = check_step(self.step)
  File "/home/ubuntu/src/flex_extract/Source/Python/Mods/checks.py", line 305, in check_step
    import numpy as np
ImportError: No module named numpy

Actually, NUMPY packaged has been installed in my python3 envrionment library, and if I only run flex_extract and retrieved global ERA5 data correctly.

Kindly tell me whether it is due to the issue of download.py and how to fix it.

**Comment by BlackFreedom** [comment]
FLEX_EXTRACT version is V7.1.2.

**Comment by Xunius** [comment]
Hi @XunZhangNJU 

From this line:

```
File "/home/ubuntu/src/flex_extract/Source/Python/Mods/checks.py", line 305, in check_step
```
it tells that the error was triggered by `flex_extract`. My script only internally calls `flex_extract`. So this seems to be an issue related to the python installation on your machine. For some reason your python doesn't see the numpy module.

Are you using any kind of python virtual environment, for instance `anaconda`? It could be possible that you installed numpy for the system-wide python, but you are running this script in a virtual environment of python where there is no numpy installed. Or you installed numpy for a different version of python than the python you are running? You will need to make sure that the very version of python you are executing can actually `import numpy`.

I would advice checking out `anaconda` and use that for virtual environment management.
Hope that helps.
